import Document, {
  Head, Main, NextScript, Html,
} from 'next/document'
import { ServerStyleSheet } from 'styled-components'

export default class MyDocument extends Document {
  static getInitialProps({ renderPage }) {
    const sheet = new ServerStyleSheet()
    const page = renderPage((App) => (props) => sheet.collectStyles(<App {...props} />))
    const styleTags = sheet.getStyleElement()
    return { ...page, styleTags }
  }

  script = () => ({
    __html: `
      if (typeof window !== "undefined") {
        window.onload = () => {
          document.getElementById("holderStyle").remove();
        };
      }
    `,
  })

  style = () => ({
    __html: `
      *, *::before, *::after {
        transition: none !important;
      }
    `,
  })

  render() {
    return (
      <Html>
        <Head>
          <title>thprsmeeting2021</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
          <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet" />
          <script dangerouslySetInnerHTML={this.script()} />
          <style id="holderStyle" dangerouslySetInnerHTML={this.style()} />
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    )
  }
}
