import { useContext, useEffect, useState } from 'react'
import styled from 'styled-components'
import Head from 'next/head'
import Router from 'next/router'
import styles from '../styles/Home.module.css'
import userContext from '../src/context/userContext'
import { ModalLogin } from '../src/components'

const Container = styled.div`
  position: relative;
  .img {
    height: 100%;
    Width: 100%;
    object-fit: cover;
  }
`

const Box = styled.div`
  border: 2px solid #F00;
  position: absolute;
  cursor: pointer;
`

const Wrapper = styled.div`
  width: 100vw;
  height: 100vh;
  background-color: #A9A699;
  display: flex;
  align-items: center;
  justify-content: center;
`

export default function Home() {
  const user = useContext(userContext)
  const [eleHeight, setHeight] = useState()

  const onResize = () => {
    const box = document.querySelector('#container')
    setHeight(box.offsetHeight)
  }

  useEffect(() => {
    window.addEventListener('resize', onResize)
    return () => window.removeEventListener('resize', onResize)
  })

  useEffect(() => {
    onResize()
  }, [])

  const getPosition = (row) => {
    const VALUE = {
      1: {
        topValue: 34,
        heightValue: 13,
        width: '26.5%',
      },
    }
    if (!eleHeight) return {}
    const top = (eleHeight * VALUE[row].topValue) / 100
    const height = (eleHeight * VALUE[row].heightValue) / 100
    return {
      top: `${top}px`,
      height,
      width: VALUE[row].width,
    }
  }

  return (
    <div className={styles.container}>
      {/* <Button onClick={() => { Router.push('/test') }}>Test</Button>
      <Button onClick={() => user.logout()}>Logout</Button> */}
      <Head>
        <title>ddspace</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet" />
      </Head>
      <Wrapper>
        <Container id="container">
          <img
            className="img"
            src="/images/lobby.png"
            alt="img"
          />
          <Box
            style={{
              ...getPosition(1),
              right: '3%',
            }}
            onClick={() => { Router.push('/test') }}
          />
          <Box
            style={{
              ...getPosition(1),
              left: '2%',
            }}
          />
        </Container>
      </Wrapper>
      <ModalLogin
        visible={!user.userData && !user.isLoading}
        onFinish={(data) => {
          user.setUser(data)
          console.log('onFinish', data)
        }}
      />
    </div>
  )
}
