import { useContext } from 'react'
import styled from 'styled-components'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import userContext from '../src/context/userContext'
import { 
  Button,
  Modal,
  Form,
  Input,
} from 'antd'
import Router from 'next/router'

const TestStyle = styled.div`
  background-color: #f00;
`

export default function Home() {
  const user = useContext(userContext)
  console.log('user:', user)
  return (
    <div className={styles.container}>
      <Button onClick={() => {Router.push('/test')}}>Test</Button>
      <TestStyle>Test</TestStyle>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Modal
        visible={!user.userData}
        closable={false}
        footer={null}
      >
        <Form
          onFinish={(data) => {
            user.setUser(data)
            console.log('onFinish', data)
          }}
        >
          <Form.Item
            label="Email"
            name="email"
            rules={[{ required: true, message: 'Please input your email!' }]}
          >
            <Input />
          </Form.Item>
          <Form.Item
            label="Name"
            name="name"
            rules={[{ required: true, message: 'Please input your name!' }]}
          >
            <Input />
          </Form.Item>
          <Form.Item
            label="Lastname"
            name="lastname"
            rules={[{ required: true, message: 'Please input your lastname!' }]}
          >
            <Input />
          </Form.Item>
          <Button type="primary" htmlType="submit">
            Submit
          </Button>
        </Form>
      </Modal>  
    </div>
  )
}
